# Generated by Django 3.2.9 on 2021-12-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='url',
            new_name='site_url',
        ),
    ]
