# Generated by Django 3.2.9 on 2021-12-15 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_rates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rates',
            old_name='content',
            new_name='project_content',
        ),
        migrations.RenameField(
            model_name='rates',
            old_name='design',
            new_name='project_design',
        ),
        migrations.RenameField(
            model_name='rates',
            old_name='usability',
            new_name='project_usability',
        ),
    ]
