# Generated by Django 3.2.9 on 2021-12-15 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_auto_20211215_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rates',
            old_name='project_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='rates',
            old_name='project_design',
            new_name='design',
        ),
        migrations.RenameField(
            model_name='rates',
            old_name='project_usability',
            new_name='usability',
        ),
    ]
